### PR TITLE
Allow all python-can interfaces

### PR DESCRIPTION
**Pull request by dzid26**
This can work on Windows. I tried Peak PCAN-USB dongle and it worked.

### CODE REVIEW

**Comment by dzid26** [comment]
Fixed GUI selector. 
image


  I tested PCAN on Windows. Some interfaces that don't have automatic channel configuration will not work...  Can you see if SocketCAN still works on Linux?

**Comment by dzid26** [comment]
...sorted selector list.

**Comment by dzid26** [comment]
I use StepperServoCANtester.py all the time, so I [added](https://github.com/dzid26/StepperServoCAN/commit/bb2a9f84b48eb48cfbd685243dfff3210455f293) it to the firmware repo. I hope you don't mind.

**Comment by killinen** [comment]
> Fixed GUI selector. image
> 
> I tested PCAN on Windows. Some interfaces that don't have automatic channel configuration will not work... Can you see if SocketCAN still works on Linux?

Sorry this took so long time, but no it did not work with my configuration: Grey Panda and Ubuntu 20.04. I tried the socketcan and socketcand from the GUI selector.

**Comment by killinen** [comment]
> I use StepperServoCANtester.py all the time, so I [added](https://github.com/dzid26/StepperServoCAN/commit/bb2a9f84b48eb48cfbd685243dfff3210455f293) it to the firmware repo. I hope you don't mind.

No, I don't mind, I think it's cool :)

**Comment by dzid26** [comment]
Now it may work actually - on my [main](https://github.com/dzid26/StepperServoCAN/commit/7a86797bccf9f99856bd1908f3024be1742e82bc#diff-223d2b12bd4046ab732f29c5c258a55cc8bc3d8db7fdcc516b2a5366582cb782R112-R116).

**Comment by killinen** [comment]
It worked. 

I made small change to the code, I deleted the connect button and changed the can_interface_selector so that it will update the interface when you change it: https://github.com/killinen/StepperServoCANtester/tree/can_interface_selector

**Comment by killinen** [comment]
> It worked.
> 
> I made small change to the code, I deleted the connect button and changed the can_interface_selector so that it will update the interface when you change it: https://github.com/killinen/StepperServoCANtester/tree/can_interface_selector

**Pull request closed without merging**
